import { Inter } from 'next/font/google';
import './globals.css';
import { ReactNode } from 'react';

export const metadata = {
  title: 'DBA App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className=" w-screen h-screen ">{children}</body>
    </html>
  );
}
